### ISSUE TITLE
[BE] Create User

### ISSUE THREAD

**Issue by sirbully** [study-pal/studypal#15]
### Tasks

- `POST` request to `/users` which will create a new user object
- User object will contain email, first name, last name, full name, photo, user type

**Comment by sirbully** [comment]
@egwilborn I changed my mind for this, let's have firebase auto generate the ID for us instead of setting the email as the unique ID per user. Please use firestore [addDoc](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document) instead of setDoc so it will take care of generating the ID.

**Comment by egwilborn** [comment]
@sirbully Hey Krizza, what would you like returned to the client after a successful user document creation?

**Comment by sirbully** [comment]
@egwilborn just userId since I'll be using the get endpoint for the other user details. Also status message if success, and failure for vice versa. Ideally we would want to wrap the firebase await functions in trycatch and return success in try and error in catch.

Error return would look like:
```
{
    "status": "error"
    "message": "message here"
}
``` 

Success default format would be:
```
{
    "status": "success"
    "data": could be an array of objects or just an object
}
```
