### ISSUE TITLE
[BE] Create Tutor endpoint

### ISSUE THREAD

**Issue by sirbully** [study-pal/studypal#9]
### Tasks

- `POST` request to `/tutor` which will create a new tutor object with a `user id` related to it
- Tutor object will contain the `user id` related to it and gender, session booking link, age group, subjects (array)
- Please use firestore [addDoc](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document) instead of setDoc to autogenerate the ID

**Comment by sophiedang0101** [comment]
@sirbully, so each tutor is supposed to have a user id? and this user id is the id of a student?

**Comment by sirbully** [comment]
@sophiedang0101 The user id is the id of the tutor. We will have 2 tables: users and tutors. The users table will contain only user-specific details like name, email, etc but the tutors table will contain tutor-specific details like subjects, age group, etc. The user id inside tutor will link to the user details in the user table 🙇‍♀️
